name: Laravel Test

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  laravel-tests-build-release:

    runs-on: ubuntu-20.04

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache composer
        uses: actions/cache@v3.3.2
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache npm dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-node-modules-
      - name: Cache npm home
        uses: actions/cache@v2
        id: npm-home
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-npm-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-home-

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - name: Create Database
        run: mysql -u root --password="root" -e "CREATE DATABASE IF NOT EXISTS natindonesia;"
      - name: Generate key
        run: php artisan key:generate
      - name: Migrate Database
        run: php artisan migrate --seed
      - name: Migration Must Pass Double Refresh
        run: |
          php artisan migrate:refresh --seed
          php artisan migrate:refresh --seed
      - name: NPM Install
        if: steps.npm-cache.outputs.cache-hit != 'true' || steps.npm-home.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build with Vite
        run: npm run build

      - name: Execute tests (Unit and Feature tests) via Pest
        run: php artisan test
